DROP TABLE IF EXISTS receipts CASCADE;

CREATE TABLE receipts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCE users(id) ON DELETE CASCADE NOT NULL,
  family_id INTEGER REFERENCE families(id) ON DELETE CASCADE NOT NULL,
  img VARCHAR(255),
  store VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  total INTEGER NOT NULL
);