DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  receipt_id INTEGER REFERENCE receipts(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255),
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  return_by DATE
);