DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255)
);

DROP TABLE IF EXISTS receipts CASCADE;

CREATE TABLE receipts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  img VARCHAR(255),
  store VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  return_by DATE NOT NULL,
  total MONEY NOT NULL
);

DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  receipt_id INTEGER REFERENCES receipts(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255),
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  return_by DATE
);

DROP TABLE IF EXISTS reminders CASCADE;

CREATE TABLE reminders (
  id SERIAL PRIMARY KEY,
  receipt_id INTEGER REFERENCES receipts(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL
);

DROP TABLE IF EXISTS images CASCADE;

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  receipt_id INTEGER REFERENCES receipts(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(50),
  image_url VARCHAR(255)
);